### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by postlund** [postlund/dlink_hnap#1]
This is more or less an import from https://github.com/postlund/hass-config/tree/master/homeassistant/custom_components/dlink_motion_sensor, but it has not yet been tested. So I can't tell if it works or not. If you try it out and it works, please report back here. Create new issues if you have any problems.

**Comment by Molodax** [comment]
It is working, thanks!
I'd love to test DCH-S160 water sensor if you decide to implement it, especially when D-link announced that they will stop supporting IFTTT.
Also, it seems that the example of the setting is missing parameter `host`

**Comment by postlund** [comment]
Great, thanks for reporting back 👍 I added host to the example. Will try to add support for water sensor as well.

**Comment by postlund** [comment]
@Molodax Maybe you can help out with #2? I think the mention didn't work.

**Comment by deadsoul69** [comment]
If there is development I have 4 DCH-S161 under the elbow ready to test ...

**Comment by Photogad** [comment]
DCH-S162 sensor seems to "work" however it stopped communicating with it after it being online for about 12 hours

**Comment by wildenrou** [comment]
Hi, I have set up an experimental integration that is cloud-based and is designed to support water leak detectors DCH-S162 (and eventually DCH-S163) . Feel free to test it and report issues. https://github.com/wildenrou/dlink_mydlink_water
