### ISSUE TITLE
Adjustable polling interval

### ISSUE THREAD

**Issue by bsniezul** [postlund/dlink_hnap#10]
I own a D-Link DCH-S150 motion sensor and I have just set it up in HA using your custom component.

I want to use it to control the light in my utility room but the sensor state updates are not frequent enough for the automation to be useful. I experience 1 - 5 second delays before the light actually turns on. I also verified that controlling the light is close to instantaneous, so I'm guessing it has to do with either this component, or the automation pipeline, or all of it combined.

Now, I am aware that this is not the best sensor to use in my case as it needs to be polled and using something MQTT-enabled would yield much better results, but I was wondering if something could be accomplished in terms of the polling frequency.

I looked through your code but I couldn't find any obvious hints as to where an adjustment could be made. I'm also new to HA, so I might be looking in the wrong place (sorry about that).

I'm running HA 0.114.1 on a Raspberry Pi 3 Model B+. `dlink_hnap` was installed using HACS.

By the way, thanks for your contribution, it's much appreciated!

**Comment by postlund** [comment]
The scan interval is five seconds as defined here:

https://github.com/postlund/dlink_hnap/blob/32438e223a7922ad66643c128d590ab7538f5e83/custom_components/dlink_hnap/binary_sensor.py#L31

You can change it with `scan_interval` in the config (it's part of how a binary sensor work). Using much lower values will likely cause instability so I don't advice it, but you are free to try of course. Low latency and polling does not go very well together I'm afraid.

**Comment by bsniezul** [comment]
Thanks for the prompt reply!

> The scan interval is five seconds as defined here:

Indeed it is, I don't know how I could've missed it!

> You can change it with scan_interval in the config (it's part of how a binary sensor work).

Thanks, didn't know that it was part of the sensor API.

> Low latency and polling does not go very well together I'm afraid.

You're absolutely right. I'm planning to replace it with a Raspberry Pi with PIR sensors wired directly to the GPIO. I just had the DCH-S150 lying around, so I figured I'd put it to use.

Again, thanks for the help!

**Comment by postlund** [comment]
No problems, wish you best of luck 😊 Feel free to report back if you try out lower scan intervals with success.
